openapi: 3.0.0
info:
  title: API Sistema Predictivo de Mantenimiento de Equipos
  version: 1.0.0
paths:
  /measurements:
    post:
      summary: Registrar una nueva medición
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Measurement'
      responses:
        '201':
          description: Medición registrada exitosamente.
    get:
      summary: Obtener datos de sensores
      parameters:
        - in: query
          name: equipmentId
          required: true
          schema:
            type: string
        - in: query
          name: startDate
          required: true
          schema:
            type: string
            format: date-time
        - in: query
          name: endDate
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Datos de sensores obtenidos exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Measurement'
  /equipments:
    post:
      summary: Crear un nuevo equipo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Equipment'
      responses:
        '201':
          description: Equipo creado exitosamente
          content:
            application/json:
              schema:
                type: string
    get:
      summary: Obtener todos los equipos
      parameters:
        - in: query
          name: type
          required: false
          schema:
            type: string
        - in: query
          name: location
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Lista de equipos obtenida exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  equipments:
                    type: array
                    items:
                      $ref: '#/components/schemas/Equipment'
                  totalCount:
                    type: integer
                  filters:
                    type: object
                    properties:
                      type:
                        type: string
                      location:
                        type: string
  /equipments/batch:
    post:
      summary: Crear múltiples equipos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Equipment'
      responses:
        '201':
          description: Equipos creados exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
components:
  schemas:
    Measurement:
      type: object
      properties:
        id:
          type: string
        equipmentId:
          type: string
        registrationDate:
          type: string
          format: date-time
        frequency:
          type: number
        current:
          type: number
        internalPressure:
          type: number
        externalPressure:
          type: number
        internalTemperature:
          type: number
        externalTemperature:
          type: number
        vibrationX:
          type: number
    Equipment:
      type: object
      properties:
        id:
          type: string
        equipmentId:
          type: string
        name:
          type: string
        type:
          type: string
        location:
          type: string
        installationDate:
          type: string
          format: date
        operatorEmails:
          type: array
          items:
            type: string
