amazon:
  dynamodb:
    endpoint: ${AMAZON_DYNAMODB_ENDPOINT}
    region: ${AMAZON_REGION}
    access-key: ${AMAZON_ACCESS_KEY}
    secret-key: ${AMAZON_SECRET_KEY}

spring:
  data:
    dynamodb:
      entity2ddl:
        auto: create-only
        gsiProjectionType: ALL
        readCapacity: 10
        writeCapacity: 1

prediction:
  model:
    bucket: predictor-model-bucket
    key: models/predictor.pmml

alert:
  screenshot:
    bucket: spme-screenshots-bucket

logging:
  level:
    org.springframework: DEBUG
