amazon:
  dynamodb:
    endpoint: http://localhost:8000
    region: us-west-2
    access-key: DUMMYIDEXAMPLE
    secret-key: DUMMYEXAMPLEKEY

spring:
  data:
    dynamodb:
      entity2ddl:
        auto: create-only
        gsiProjectionType: ALL
        readCapacity: 10
        writeCapacity: 1

prediction:
  model:
    path: /home/clizcano/Documentos/GitHub/AI4Devs/AI4Devs-finalproject/backend/src/main/resources/models/predictor.pmml
