amazon:
  dynamodb:
    endpoint: https://30ec-2800-484-4482-5480-5274-b367-897e-12e3.ngrok-free.app
    region: us-west-2
    access-key: DUMMYIDEXAMPLE
    secret-key: DUMMYEXAMPLEKEY

spring:
  data:
    dynamodb:
      entity2ddl:
        auto: create-only
        gsiProjectionType: ALL
        readCapacity: 10
        writeCapacity: 1

prediction:
  model:
    path: /home/clizcano/Documentos/GitHub/AI4Devs/AI4Devs-finalproject/backend/src/main/resources/models/predictor.pmml

alert:
  screenshot:
    path: ${user.dir}/resources/alerts/screenshots/
